export default {
    products: [
      {
        _id: '111111111111111111111111',
        name: 'Hiskywin Full Zip Running Shirts Thermal Workout',
        category: 'Shirts',
        image: '/images/product-1.jpg',
        price: 59,
        brand: 'Hiskywin',
        rating: 4.5,
        numReviews: 10,
        description:"Good Product",
        countInStock: 6,
      },
      {
        _id: '222222222222222222222222',
        name: 'Nike Full-Zip Hoodie Mens Workout Sweatshirt',
        category: 'Shirts',
        image: '/images/product-2.jpg',
        price: 70,
        brand: 'Nike',
        description:"nice Product",
        rating: 5,
        numReviews: 51,
        countInStock: 2,
      },
      {
        _id: '333333333333333333333333',
        name: 'Adidas Mens Long Sleeve Hoodie',
        category: 'Shirts',
        image: '/images/product-3.jpg',
        price: 59,
        brand: 'Adidas',
        description:"Good Product",
        rating: 4,
        numReviews: 45,
        countInStock: 1,
      },
      {
        _id: '444444444444444444444444',
        name: 'Under Armour Mens Sportstyle Tricot Joggers',
        category: 'Pants',
        image: '/images/product-4.jpg',
        price: 90,
        brand: 'Under Armour',
        description:"nice Product",
        rating: 2.5,
        numReviews: 198,
        countInStock: 3,
      },
      {
        _id: '555555555555555555555555',
        name: 'Champion Mens Graphic Powerblend Fleece Jogger',
        category: 'Pants',
        image: '/images/product-5.jpg',
        price: 119,
        brand: 'Champion',
        description:"Good Product",
        rating: 3.5,
        numReviews: 89,
        countInStock: 4,
      },
      {
        _id: '666666666666666666666666',
        name: 'Aelfric Eden Mens Joggers Pants Long Multi-Pockets',
        category: 'Pants',
        image: '/images/product-6.jpg',
        price: 85,
        brand: 'Aelfric Eden',  
        description:"nice Product",
        rating: 4.5,
        numReviews: 45,
        countInStock: 8,
      },
    ],
  };